### ISSUE TITLE
unmarshal error returned at get curriculums

### ISSUE THREAD

**Issue by stafel** [SmashGrade/backend#23]
Tested on branch feat/endpoints with testdata generated by main.go/generateTestdata

Steps to reproduce issue:
build and run container:
podman build -t tb .
podman run --rm -p 9000:9000 tb
In the browser call get curriculums entpoint ( http://localhost:9000/api/v1/curriculum ) with at least one curriculum in db.
Returns "json: cannot unmarshal object into Go struct field CurriculumRes.focus of type string"

Expected result: json list of curriculums

**Comment by FerberJ** [comment]
bug fixed.

I added the tag json:"-" to Focus and Curriculumtype in entity.Curriculum. That way it wont be parsed into json and the GET works.

**Comment by stafel** [comment]
Thanks,
just checked it, works now
![image](https://github.com/SmashGrade/backend/assets/109684782/757cc230-b04a-4c04-bce3-d2555da0a7fd)
