### ISSUE TITLE
backend returns 502 error on endpoints with path parameters

### ISSUE THREAD

**Issue by stafel** [SmashGrade/backend#36]
to reproduce:
open https://api.smashgrade.ch/docs/
check get /courses you will find course id 1 version 1 there
check get /courses/:id/:version with id: 1 and version: 1
return "502 Bad Gateway nginx"

this also happens with create /courses/:id, put /courses/:id/:version and delete /courses/:id/:version

**Comment by pr0ton11** [comment]
Happens when the application crashes and the reverse proxy does not get any response. Since we closed a few bugs regarding this, I am going to close this as resolved.
